# Generated by Django 5.2.7 on 2026-03-31 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_pac',
            new_name='add_package',
        ),
    ]
