# Generated by Django 5.2.7 on 2026-04-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_rename_add_pac_add_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_package',
            name='duration',
            field=models.IntegerField(default=3, max_length=50),
            preserve_default=False,
        ),
    ]
