# Generated by Django 5.2.7 on 2026-04-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_add_package_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_package',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
