# Generated by Django 5.2.7 on 2026-03-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10000)),
                ('travel_date', models.DateField(max_length=100)),
                ('travelers', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=1000)),
                ('spec_req', models.CharField(max_length=1000)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
