# Generated by Django 5.2.7 on 2026-04-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtemp',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
