# Generated by Django 5.2.7 on 2026-04-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripza', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtemp',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
