# Generated by Django 5.2.7 on 2026-04-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
